(function(factory){if(typeof define==='function'&&define.amd){define(factory);}else{window.pym=factory.call(this);}})(function(){var MESSAGE_DELIMITER='xPYMx';var lib={};var _getParameterByName=function(name){var regex=new RegExp("[\\?&]"+ name.replace(/[\[]/,'\\[').replace(/[\]]/,'\\]')+'=([^&#]*)');var results=regex.exec(location.search);if(results===null){return'';}
return decodeURIComponent(results[1].replace(/\+/g," "));};var _isSafeMessage=function(e,settings){if(settings.xdomain!=='*'){if(!e.origin.match(new RegExp(settings.xdomain+'$'))){return;}}
return true;};var _makeMessage=function(id,messageType,message){var bits=['pym',id,messageType,message];return bits.join(MESSAGE_DELIMITER);};var _makeMessageRegex=function(id){var bits=['pym',id,'(\\S+)','(.+)'];return new RegExp('^'+ bits.join(MESSAGE_DELIMITER)+'$');};var _autoInit=function(){var elements=document.querySelectorAll('[data-pym-src]:not([data-pym-auto-initialized])');var length=elements.length;for(var idx=0;idx<length;++idx){var element=elements[idx];element.setAttribute('data-pym-auto-initialized','');if(element.id===''){element.id='pym-'+ idx;}
var src=element.getAttribute('data-pym-src');var xdomain=element.getAttribute('data-pym-xdomain');var config={};if(xdomain){config.xdomain=xdomain;}
new lib.Parent(element.id,src,config);}};lib.Parent=function(id,url,config){this.id=id;this.url=url;this.el=document.getElementById(id);this.iframe=null;this.settings={xdomain:'*'};this.messageRegex=_makeMessageRegex(this.id);this.messageHandlers={};this._constructIframe=function(){var width=this.el.offsetWidth.toString();this.iframe=document.createElement("iframe");var hash='';var hashIndex=this.url.indexOf('#');if(hashIndex>-1){hash=this.url.substring(hashIndex,this.url.length);this.url=this.url.substring(0,hashIndex);}
if(this.url.indexOf('?')<0){this.url+='?';}else{this.url+='&';}
this.iframe.src=this.url+'initialWidth='+ width+'&childId='+ this.id+ hash;this.iframe.setAttribute('width','100%');this.iframe.setAttribute('scrolling','no');this.iframe.setAttribute('marginheight','0');this.iframe.setAttribute('frameborder','0');this.el.appendChild(this.iframe);var that=this;window.addEventListener('resize',function(){that.sendWidth();});};this._fire=function(messageType,message){if(messageType in this.messageHandlers){for(var i=0;i<this.messageHandlers[messageType].length;i++){this.messageHandlers[messageType][i].call(this,message);}}};this._processMessage=function(e){if(!_isSafeMessage(e,this.settings)){return;}
var match=e.data.match(this.messageRegex);if(!match||match.length!==3){return false;}
var messageType=match[1];var message=match[2];this._fire(messageType,message);};this._onHeightMessage=function(message){var height=parseInt(message);this.iframe.setAttribute('height',height+'px');};this.onMessage=function(messageType,callback){if(!(messageType in this.messageHandlers)){this.messageHandlers[messageType]=[];}
this.messageHandlers[messageType].push(callback);};this.sendMessage=function(messageType,message){this.el.getElementsByTagName('iframe')[0].contentWindow.postMessage(_makeMessage(this.id,messageType,message),'*');};this.sendWidth=function(){var width=this.el.offsetWidth.toString();this.sendMessage('width',width);};for(var key in config){this.settings[key]=config[key];}
this.onMessage('height',this._onHeightMessage);var that=this;window.addEventListener('message',function(e){return that._processMessage(e);},false);this._constructIframe();return this;};lib.Child=function(config){this.parentWidth=null;this.id=null;this.settings={renderCallback:null,xdomain:'*',polling:0};this.messageRegex=null;this.messageHandlers={};this.onMessage=function(messageType,callback){if(!(messageType in this.messageHandlers)){this.messageHandlers[messageType]=[];}
this.messageHandlers[messageType].push(callback);};this._fire=function(messageType,message){if(messageType in this.messageHandlers){for(var i=0;i<this.messageHandlers[messageType].length;i++){this.messageHandlers[messageType][i].call(this,message);}}};this._processMessage=function(e){if(!_isSafeMessage(e,this.settings)){return;}
var match=e.data.match(this.messageRegex);if(!match||match.length!==3){return;}
var messageType=match[1];var message=match[2];this._fire(messageType,message);};this.sendMessage=function(messageType,message){window.top.postMessage(_makeMessage(this.id,messageType,message),'*');};this.sendHeight=function(){var height=document.getElementsByTagName('body')[0].offsetHeight.toString();this.sendMessage('height',height);};this._onWidthMessage=function(message){var width=parseInt(message);if(width!==this.parentWidth){this.parentWidth=width;if(this.settings.renderCallback){this.settings.renderCallback(width);}
this.sendHeight();}};this.id=_getParameterByName('childId');this.messageRegex=new RegExp('^pym'+ MESSAGE_DELIMITER+ this.id+ MESSAGE_DELIMITER+'(\\S+)'+ MESSAGE_DELIMITER+'(.+)$');var width=parseInt(_getParameterByName('initialWidth'));this.onMessage('width',this._onWidthMessage);for(var key in config){this.settings[key]=config[key];}
var that=this;window.addEventListener('message',function(e){that._processMessage(e);},false);if(this.settings.renderCallback){this.settings.renderCallback(width);}
this.sendHeight();if(this.settings.polling){window.setInterval(this.sendHeight,this.settings.polling);}
return this;};_autoInit();return lib;});