var graphic=$('#graphic');var menu=$("#menu");var dvc={};var pymChild=null;var height;var chart_width;var circleScale;var margin;var svg;dvc.y1_value;dvc.y2_value;var num_ticksx;var num_ticksy;var buttons=$("#buttons");buttonsWidth=buttons.width();var isOpera=!!window.opera||navigator.userAgent.indexOf(' OPR/')>=0;var isFirefox=typeof InstallTrigger!=='undefined';var isSafari=Object.prototype.toString.call(window.HTMLElement).indexOf('Constructor')>0;var isChrome=!!window.chrome&&!isOpera;var isIE=/*@cc_on!@*/false||!!document.documentMode;var output='Detecting browsers by ducktyping:		';output+='isFirefox: '+ isFirefox+'		';output+='isChrome: '+ isChrome+'		';output+='isSafari: '+ isSafari+'		';output+='isOpera: '+ isOpera+'		';output+='isIE: '+ isIE+'		';function drawGraphic()
{var threshold_md=788;var threshold_sm=dvc.config.optional.mobileBreakpoint;d3.selectAll(".lineComponents").remove();if(graphic.width()<threshold_sm){margin={top:dvc.config.optional.margin_sm[0],right:dvc.config.optional.margin_sm[1],bottom:dvc.config.optional.margin_sm[2],left:dvc.config.optional.margin_sm[3]};chart_width=graphic.width()- margin.left- margin.right;height=Math.ceil((chart_width*dvc.config.optional.aspectRatio_sm[1])/ dvc.config.optional.aspectRatio_sm[0]);num_ticksx=dvc.config.optional.x_num_ticks_sm_md_lg[0];num_ticksy=dvc.config.optional.y_num_ticks_sm_md_lg[0];}else if(graphic.width()<threshold_md){margin={top:dvc.config.optional.margin_md[0],right:dvc.config.optional.margin_md[1],bottom:dvc.config.optional.margin_md[2],left:dvc.config.optional.margin_md[3]};chart_width=graphic.width()- margin.left- margin.right;height=Math.ceil((chart_width*dvc.config.optional.aspectRatio_sm[1])/ dvc.config.optional.aspectRatio_sm[0]);num_ticksx=dvc.config.optional.x_num_ticks_sm_md_lg[1];num_ticksy=dvc.config.optional.y_num_ticks_sm_md_lg[1];}else{margin={top:dvc.config.optional.margin_lg[0],right:dvc.config.optional.margin_lg[1],bottom:dvc.config.optional.margin_lg[2],left:dvc.config.optional.margin_lg[3]}
chart_width=graphic.width()- margin.left- margin.right;height=Math.ceil((chart_width*dvc.config.optional.aspectRatio_lg[1])/ dvc.config.optional.aspectRatio_lg[0]);num_ticksx=dvc.config.optional.x_num_ticks_sm_md_lg[2];num_ticksy=dvc.config.optional.y_num_ticks_sm_md_lg[2];}
graphic.empty();menu.empty();dvc.Padding_top=margin.top;dvc.Padding_right=margin.right;dvc.Padding_left=margin.left;dvc.Padding_bottom=margin.bottom;dots={};values=[];for(var column in graphic_data[0]){dots=graphic_data.map(function(d,i){values.push(d.value);return{'group':d.group,'name':d.name,'0':+d["Healthy Life Expectancy"],'1':+d["Inequality within local authority"],'2':+d["Healthy Life Expectancy "],'3':+d["Inequality within local authority "],'4':+d.var4,'5':+d.var5,'value':+d.value};});}
circleScale=d3.scale.sqrt().domain([0,d3.max(values)]).range([0,7]);svg=d3.select('#graphic').append('svg').attr("width",chart_width+ margin.left+ margin.right).attr("height",height+ margin.top+ margin.bottom+50).append("g").attr("transform","translate("+ margin.left+","+(margin.top)+")");svg.append("defs").append("clipPath").attr("id","clip").append("rect").attr("width",chart_width- margin.left- margin.right).attr("height",height);var valueArray=[];for(var i=0;i<dvc.config.vars.variables.length;i++){valueArray[i]=i;}
var YdataVariablesArrays=d3.zip(dvc.config.vars.variables,valueArray);dvc.YdataVariablesArrays=YdataVariablesArrays.sort(function(b,a){return d3.descending(a[0],b[0])});if(dvc.config.vars.dropOpt.length>0){var valueArray=[];for(var i=0;i<dvc.config.vars.dropOpt.length;i++){valueArray[i]=i;}
$('#varselect').chosen({width:"20%",allow_single_deselect:true,disable_search:true,placeholder_text_single:""}).on('change',function(evt,params)
{if(typeof params!='undefined')
{dvc.limitTypeIndex=params.selected;dvc.selectedXVariable=dvc.config.vars.variables[(dvc.limitTypeIndex*2)];dvc.selectedYVariable=dvc.config.vars.variables[(dvc.limitTypeIndex*2)+1];dvc.selectedXVariableIndex=dvc.config.vars.variables.indexOf(dvc.selectedXVariable);dvc.selectedYVariableIndex=dvc.config.vars.variables.indexOf(dvc.selectedYVariable);transitionData();}
else{}});}
dvc.xData=[];dvc.yData=[];dots.forEach(function(d,i){var x=+d[dvc.selectedXVariableIndex];var y=+d[dvc.selectedYVariableIndex];dvc.xData.push(+d[dvc.selectedXVariableIndex]);dvc.yData.push(+d[dvc.selectedYVariableIndex]);});dvc.xDomain=dvc.config.essential.AxisScale;dvc.yDomain=dvc.config.essential.AxisScale;x=d3.scale.linear().domain(dvc.xDomain).range([margin.left,chart_width]);dvc.xAxis=d3.svg.axis().scale(x).orient("bottom").ticks(num_ticksx).tickFormat(d3.format(",."+ dvc.config.essential.xaxislabelPrecison+"f"));svg.append("g").attr("class","x axis").attr("id","focusXAxis").attr("transform","translate(0,"+(height+ dvc.Padding_top)+")").call(dvc.xAxis);y=d3.scale.linear().domain(dvc.yDomain).range([(height),0]);dvc.yAxis=d3.svg.axis().scale(y).orient("left").ticks(num_ticksy).tickFormat(d3.format(",."+ dvc.config.essential.yaxislabelPrecison+"f"));svg.append("g").attr("class","y axis").attr("id","focusYAxis").attr("transform","translate("+ dvc.Padding_left+","+ dvc.Padding_top+")").call(dvc.yAxis);dvc.xticks=svg.selectAll('#focusXAxis').selectAll('.tick');dvc.xticks.append('svg:line').attr('id',"xAxisTicks").attr('y0',0).attr('y1',-height).attr('x1',0).attr('x2',0).style("opacity",0.33);dvc.yticks=svg.selectAll('#focusYAxis').selectAll('.tick');dvc.yticks.append('svg:line').attr('id',"yAxisTicks").attr('y0',0).attr('y1',0).attr('x1',0).attr('x2',chart_width- margin.left).style("opacity",0.33);svg.append("text").attr('class','unit').attr('id','yAxisLabel').attr("x",x(dvc.xDomain[0])-35).attr("y",y(dvc.yDomain[1])).attr("text-anchor","start").text("Total exports £ million");svg.append("text").attr('class','unit').attr('id','xAxisLabel').attr("x",x(dvc.xDomain[1])).attr("y",y(dvc.yDomain[0])+ margin.top+ 40).attr("text-anchor","end").text("Total imports £ million");svg.append("p").attr('class','unit').attr('id','xAxisLabel').attr("x",x(dvc.xDomain[1])).attr("y",y(dvc.yDomain[0])+ margin.top+ 40).attr("text-anchor","end").text("Total imports £ mililon");if(dvc.config.optional.vertical_line==true){dvc.config.optional.annotateLineX1_Y1_X2_Y2.forEach(function(d,i){svg.append("line").attr('x1',x(dvc.config.optional.annotateLineX1_Y1_X2_Y2[i][0][0])).attr('x2',x(dvc.config.optional.annotateLineX1_Y1_X2_Y2[i][1][0])).style('stroke','#888').style('stroke-width',2).style('stroke-dasharray','5 5').attr('y1',y(dvc.config.optional.annotateLineX1_Y1_X2_Y2[i][0][1])).attr('y2',y(dvc.config.optional.annotateLineX1_Y1_X2_Y2[i][1][1])).attr("transform","translate(0,"+(dvc.Padding_top)+")");})}
calculateYValues();writeAnnotation();function writeAnnotation(){if(graphic.width()<threshold_sm){dvc.config.essential.annotationChart.forEach(function(d,i){svg.append("text").text(dvc.config.essential.annotationBullet[i]).attr("class","annotext"+ i+" annotext").attr("text-anchor",dvc.config.essential.annotationAlign[i]).attr('y',y(dvc.config.essential.annotationXY[i][1])+ margin.top).attr('x',x(dvc.config.essential.annotationXY[i][0]));d3.selectAll(".annotext"+(i)).each(insertLinebreaks).each(createBackRect);function insertLinebreaks(){var str=this;var el1=dvc.config.essential.annotationBullet[i];var el=el1.data;var words=el1.split('  ');d3.select(this).text('');for(var j=0;j<words.length;j++){var tspan=d3.select(this).append('tspan').text(words[j]);if(j>0)
tspan.attr('x',x(dvc.config.essential.annotationXY[i][0])).attr('dy','22');}};function createBackRect(){var BBox=this.getBBox()
svg.insert("rect",".annotext"+(i)).attr("width",BBox.width).attr("height",BBox.height).attr("x",BBox.x).attr("y",BBox.y).attr("fill","white").attr("opacity",0.4);};if(dvc.config.essential.circles==true){}});}
else{dvc.config.essential.annotationChart.forEach(function(d,i){svg.append("text").text(dvc.config.essential.annotationChart[i]).attr("class","annotext"+ i+" annotext").attr("text-anchor",dvc.config.essential.annotationAlign[i]).attr('y',y(dvc.config.essential.annotationXY[i][1])+ margin.top).attr('x',x(dvc.config.essential.annotationXY[i][0]));d3.selectAll(".annotext"+(i)).each(insertLinebreaks).each(createBackRect);function insertLinebreaks(){var str=this;var el1=dvc.config.essential.annotationChart[i];var el=el1.data;var words=el1.split('  ');d3.select(this).text('');for(var j=0;j<words.length;j++){var tspan=d3.select(this).append('tspan').text(words[j]);if(j>0)
tspan.attr('x',x(dvc.config.essential.annotationXY[i][0])).attr('dy','22');}};function createBackRect(){var BBox=this.getBBox()
svg.insert("rect",".annotext"+(i)).attr("width",BBox.width).attr("height",BBox.height).attr("x",BBox.x).attr("y",BBox.y).attr("fill","white").attr("opacity",0.4);};if(dvc.config.essential.circles==true){}});}
return;}
svg.selectAll(".circle").data(dots).enter().append("circle").attr("class",function(d,i){return"circles "+ d.group;}).attr("id",function(d,i){return"circle"+ i;}).attr("cx",function(d,i){return x(d[dvc.selectedXVariableIndex]);}).attr("cy",function(d,i){return y(d[dvc.selectedYVariableIndex])+dvc.Padding_top;}).attr("r",5).style("fill",function(d,i){if(d[dvc.selectedXVariableIndex]>d[dvc.selectedYVariableIndex])
{return"#ED028C"}else
{return"#1074BC"}}).style("stroke",function(d,i){if(d[dvc.selectedXVariableIndex]>d[dvc.selectedYVariableIndex])
{return"#ED028C"}else
{return"#1074BC"}}).attr("opacity",function(d,i){if(dvc.booleanButtons[dvc.config.vars.groups.indexOf(d.group)]==true||dvc.booleanButtons.indexOf(true)==-1){return 1.00;}
else{return 0.5;}}).attr("fill-opacity",function(d,i){if(dvc.booleanButtons[dvc.config.vars.groups.indexOf(d.group)]==true||dvc.booleanButtons.indexOf(true)==-1){return 0.50;}
else{return 0.50;}}).attr("display","inline");var voronoi=d3.geom.voronoi().x(function(d,i){return x(d[dvc.selectedXVariableIndex]);}).y(function(d,i){return y(d[dvc.selectedYVariableIndex])+dvc.Padding_top;}).clipExtent([[margin.left-5,margin.top-5],[chart_width-margin.left+ 15,height+ margin.top+ 5]]);svg.append("g").attr("id","voronoiGridFull");d3.select("#voronoiGridFull").selectAll("path").data(voronoi(dots)).enter().append("path").attr("d",function(d,i){if(typeof d!=='undefined'){return"M"+ d.join("L")+"Z";}
else{return;}}).datum(function(d,i){if(typeof d!=='undefined'){return d.point;}
else{return;}}).attr("class",function(d,i){if(typeof d!=='undefined'){return"voronoi "+ d.group;}
else{return;}}).attr("id",function(d,i){return"voronoi"+ i;}).style("stroke","none").style("fill","none").style("pointer-events","all").on("mouseover",function(d,i){d3.select("#voronoiGridTemp").remove();d3.selectAll(".TEMPcircles").remove();d3.select("#SelectedyAxisValueLabel").remove();d3.select("#SelectedxAxisValueLabel").remove();getSelectedReferenceInfo(this.id);if($('#'+ dvc.selectedCircleID).attr("class").indexOf("disabled")==-1&&(graphic.width()>dvc.config.optional.mobileBreakpoint)){d3.selectAll('.circles').style("opacity",0.5).style("fill-opacity",0.125);d3.select('#'+ dvc.selectedCircleID).style("opacity",1.0).style("fill-opacity",1.0);var xValue=d[dvc.selectedXVariableIndex];var yValue=d[dvc.selectedYVariableIndex];var coordinates=d3.mouse(this);dvc.x1=coordinates[0];dvc.y1=coordinates[1];showCoords();showTooltip(d,this.id,xValue,yValue,"FULL");}}).on("mouseout",function(d,i){d3.select('#'+ dvc.selectedCircleID).style("display","inline");if(dvc.booleanButtons.indexOf(true)==-1){d3.selectAll(".circles").attr("class",function(d,i){return"circles "+"grp0";}).attr("fill",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).attr("stroke",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).style("opacity",1.00).style("fill-opacity",0.50);}
else{d3.selectAll('.circles').attr("class",function(d,i){return"circles disabled "+ d.group;}).style("stroke","solid").style("stroke","#666").style("fill","#666").style("opacity",0.5).style("pointer-events","none");var index=dvc.config.vars.groups.indexOf(dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]);var color=dvc.config.vars.grpColorArray[index];d3.selectAll('.circles'+'.'+ dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]).attr("class","circles "+ dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]).style("stroke","solid").style("stroke",color).style("fill",color).style("opacity",1.00).style("fill-opacity",0.50).style("pointer-events","auto");}
removeTooltip();});svg.append("input").attr("type","check").attr("id","equality").attr("onClick","getState(this.id)");svg.append("input").attr("type","check").attr("id","regression").attr("onClick","getState(this.id)");d3.select("#equality").attr("x",50).attr("y",50);if(isIE==true){$("#regression").prop("position","absolute").prop("left","0px").prop("top","0px");}
else{d3.select("#regression").style("position","absolute").style("left","0px").style("top","0px");}
if(isIE==true){$("#equality").prop("position","absolute").prop("left","0px").prop("top","0px");}
else{d3.select("#equality").style("position","absolute").style("left","0px").style("top","0px");}
if(pymChild){pymChild.sendHeight();}
return;}
function calculateYValues()
{dvc.xValIncrement=x(1)- x(0);dvc.yValIncrement=y(0)- y(1);dvc.xDomainArray=x.domain();dvc.yDomainArray=y.domain();dvc.min_min_VariableValue=d3.min([dvc.xDomainArray[0],dvc.yDomainArray[0]]);dvc.max_min_VariableValue=d3.max([dvc.xDomainArray[0],dvc.yDomainArray[0]]);dvc.min_max_VariableValue=d3.min([dvc.xDomainArray[1],dvc.yDomainArray[1]]);dvc.max_max_VariableValue=d3.max([dvc.xDomainArray[1],dvc.yDomainArray[1]]);if(dvc.xDomainArray[0]>dvc.yDomainArray[0]){dvc.y1_value=height-((dvc.max_min_VariableValue- dvc.min_min_VariableValue)*dvc.yValIncrement);dvc.y2_value=height-((dvc.max_max_VariableValue+(dvc.max_min_VariableValue- dvc.min_min_VariableValue))*dvc.yValIncrement);}
else if(dvc.xDomainArray[0]<dvc.yDomainArray[0]){dvc.y1_value=height-((dvc.min_min_VariableValue- dvc.max_min_VariableValue)*dvc.yValIncrement);dvc.y2_value=height-((dvc.max_max_VariableValue+(dvc.min_min_VariableValue- dvc.max_min_VariableValue))*dvc.yValIncrement);}
else{dvc.y1_value=height-((dvc.min_min_VariableValue- dvc.max_min_VariableValue)*dvc.yValIncrement);dvc.y2_value=height-((dvc.max_max_VariableValue)*dvc.yValIncrement);}
return;}
function buildUI(){if(dvc.config.vars.groups.length>1){var pillWidthPercentWidth=(100/dvc.config.vars.groups.length);d3.select("#groupButtons").append("div").attr("class","btn-group").attr("id","simple-justified-button-groupGrps");d3.select("#simple-justified-button-groupGrps").append("div").attr("class","btn-group btn-group-justified").attr("id","justifiedBtnGrp").attr("role","group").attr("aria-label","Justified button group");dvc.config.vars.groups.forEach(function(d,i){var fid=d;var str=(d.toString()).replace(' ','');d3.select("#justifiedBtnGrp").append("a").attr("href","#").attr("class","btn btn-default selectGroup").attr("id",str).text(d).style("text-align","center").style("border-style","solid").style("border-width","1px").style("border-color","white").attr("onClick","clickPillGroups(this.id)");})
d3.select("#groupButtonsColors").append("div").attr("class","btn-group").attr("id","simple-justified-button-groupGrpsColors");d3.select("#simple-justified-button-groupGrpsColors").append("div").attr("class","btn-group btn-group-justified").attr("id","justifiedBtnGrpColors").attr("role","group").attr("aria-label","Justified button group");dvc.config.vars.groups.forEach(function(d,i){var str=(d.toString()).replace(' ','');d3.select("#justifiedBtnGrpColors").append("div").attr("class","btn-group btn-group-justified colorPanel").attr("id","panel"+ str).style("background-color",dvc.config.vars.grpColorArray[i]).style("text-align","center").style("width",pillWidthPercentWidth+"%").style("height","10px").style("border-style","solid").style("border-width","1px").style("border-color","white").style("opacity",1.00);})
d3.select("#Showall").attr("class","btn btn-default selectGroup disabled");d3.select("#panelShowall").style("opacity",0.33);}
else{d3.select("#groups").attr("class","row hide");}
return;}
function clickPillGroups(fid){selectedBtnIndex=dvc.config.vars.groups.indexOf(fid);selectedGrpBtn=fid;dvc.config.vars.groups.forEach(function(d,i)
{var str=(d.toString()).replace(' ','');d3.select("#"+ str).attr("class","btn btn-default selectGroup");d3.select("#panel"+ str).style("opacity",0.33);d3.select("#"+ str).style("pointer-events","auto");})
d3.select("#"+ fid).attr("class","btn btn-default selectGroup active");d3.select("#"+ fid).style("pointer-events","none");d3.select("#panel"+ fid).style("opacity",1.0);dvc.booleanButtons.forEach(function(d,i){if(i==dvc.config.vars.groups.indexOf(fid)){if(dvc.booleanButtons[i]==false){dvc.booleanButtons[i]=true;}
else{dvc.booleanButtons[i]=false;}}
else
{dvc.booleanButtons[i]=false;}})
if(fid=="Showall"){d3.select("#voronoiGridFull").style("display","inline");d3.select("#voronoiGridTemp").remove();d3.selectAll(".TEMPcircles").remove();d3.selectAll(".circles").attr("class",function(d,i){return"circles "+ d.group;}).attr("fill",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).attr("stroke",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).style("opacity",1.00).style("fill-opacity",0.50);dvc.tempDotArray=[];transitionData();}
else{d3.select("#voronoiGridTemp").remove();d3.selectAll(".TEMPcircles").remove();d3.selectAll('.circles').attr("class",function(d,i){return"circles disabled "+ d.group;}).style("stroke","solid").style("stroke","#666").style("fill","#666").style("opacity",0.5).style("pointer-events","none");var index=dvc.config.vars.groups.indexOf(fid);var color=dvc.config.vars.grpColorArray[index];d3.selectAll('.circles'+'.'+ fid).attr("class","circles "+ fid).style("stroke","solid").style("stroke",color).style("fill",color).style("opacity",1.00).style("fill-opacity",0.50).style("pointer-events","auto");dvc.selectedGroup=fid;dvc.selectedGroupIndex=dvc.config.vars.groups.indexOf(fid);document.getElementById("selectGroup").selectedIndex=dvc.selectedGroupIndex;document.getElementById("selectGroup_chosen").selectedIndex=dvc.selectedGroupIndex;$('#selectGroup').val(dvc.selectedGroupIndex);$('#selectGroup').trigger("chosen:updated");dvc.tempDotArray=[];dvc.tempDotArray=dots.filter(function(d,i){return d.group==fid;});svg.selectAll(".TEMPcircles").data(dvc.tempDotArray).enter().append("circle").attr("class",function(d,i){return"TEMPcircles "+ d.group;}).attr("id",function(d,i){return"TEMPcircle"+ i;}).attr("cx",function(d,i){return x(d[dvc.selectedXVariableIndex]);}).attr("cy",function(d,i){return y(d[dvc.selectedYVariableIndex])+dvc.Padding_top;}).attr("r",function(d,i){return 5}).attr("fill",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).attr("stroke",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).attr("opacity",function(d,i){if(dvc.booleanButtons[dvc.config.vars.groups.indexOf(d.group)]==true||dvc.booleanButtons.indexOf(true)==-1){return 0.00;}
else{return 0.00;}}).attr("fill-opacity",function(d,i){if(dvc.booleanButtons[dvc.config.vars.groups.indexOf(d.group)]==true||dvc.booleanButtons.indexOf(true)==-1){return 0.00;}
else{return 0.00;}}).attr("display","inline");var voronoi=d3.geom.voronoi().x(function(d,i){return x(d[dvc.selectedXVariableIndex]);}).y(function(d,i){return y(d[dvc.selectedYVariableIndex])+dvc.Padding_top;}).clipExtent([[margin.left-5,margin.top-5],[chart_width-margin.left+ 15,height+ margin.top+ 5]]);svg.append("g").attr("id","voronoiGridTemp");d3.select("#voronoiGridTemp").selectAll("path").data(voronoi(dvc.tempDotArray)).enter().append("path").attr("d",function(d,i){if(typeof d!=='undefined'){return"M"+ d.join("L")+"Z";}
else{return;}}).datum(function(d,i){if(typeof d!=='undefined'){return d.point;}
else{return;}}).attr("class",function(d,i){if(typeof d!=='undefined'){return"voronoiTEMP "+ d.group;}
else{return;}}).attr("id",function(d,i){return"voronoiTEMP"+ i;}).style("stroke",function(d,i){return"none";}).style("fill","none").style("pointer-events","all").on("mouseover",function(d,i){if(graphic.width()>dvc.config.optional.mobileBreakpoint){dvc.selectedCircleID='';d3.select("#SelectedyAxisValueLabel").remove();d3.select("#SelectedxAxisValueLabel").remove();getSelectedReferenceInfo(this.id);var xValue=d[dvc.selectedXVariableIndex];var yValue=d[dvc.selectedYVariableIndex];showTooltip(d,this.id,xValue,yValue,"TEMP");d3.select("#horiReferenceLine").attr("x1",x(dvc.xDomain[0])-5).attr("x2",x(d[dvc.selectedXVariableIndex])).attr("y1",margin.top+ y(d[dvc.selectedYVariableIndex])).attr("y2",margin.top+ y(d[dvc.selectedYVariableIndex])).style("stroke",function(d,i){if(dvc.config.vars.groups.length>1){return dvc.color;}
else{return dvc.config.vars.singleColor;}}).style("display","inline");d3.select("#horiReferenceBox").attr("x",x(d[dvc.selectedXVariableIndex])-25).attr("y",margin.top+ y(dvc.yDomain[0])+5).attr("width",50).attr("height",30).style("stroke",function(d,i){if(dvc.config.vars.groups.length>1){return dvc.color;}
else{return dvc.config.vars.singleColor;}}).attr("rx",5).attr("ry",5).style("display","inline");d3.select("#vertReferenceLine").attr("x1",x(d[dvc.selectedXVariableIndex])).attr("x2",x(d[dvc.selectedXVariableIndex])).attr("y1",margin.top+ y(d[dvc.selectedYVariableIndex])).attr("y2",margin.top+ y(dvc.yDomain[0])+5).style("stroke",function(d,i){if(dvc.config.vars.groups.length>1){return dvc.color;}
else{return dvc.config.vars.singleColor;}}).style("display","inline");d3.select("#vertReferenceBox").attr("x",x(dvc.xDomain[0])-55).attr("y",margin.top+ y(d[dvc.selectedYVariableIndex])-15).attr("width",50).attr("height",30).style("stroke",function(d,i){if(dvc.config.vars.groups.length>1){return dvc.color;}
else{return dvc.config.vars.singleColor;}}).attr("rx",5).attr("ry",5).style("display","inline");svg.append("text").attr("class","referenceItems").attr('id','SelectedyAxisValueLabel').attr("x",x(dvc.xDomain[0])-30).attr("y",margin.top+ y(d[dvc.selectedYVariableIndex])+5).style("font-size","12px").style("stroke","none").style("stroke",function(d,i){if(dvc.config.vars.groups.length>1){return dvc.color;}
else{return dvc.config.vars.singleColor;}}).attr("text-anchor","middle").text(yValue.toFixed(1));svg.append("text").attr("class","referenceItems").attr('id','SelectedxAxisValueLabel').attr("x",x(d[dvc.selectedXVariableIndex])).attr("y",margin.top+ y(dvc.yDomain[0])+25).style("font-size","12px").style("stroke","none").style("stroke",function(d,i){if(dvc.config.vars.groups.length>1){return dvc.color;}
else{return dvc.config.vars.singleColor;}}).attr("text-anchor","middle").text(xValue.toFixed(1));}}).on("mouseout",function(d,i){d3.select('#'+ dvc.selectedCircleID).style("display","inline");if(dvc.booleanButtons.indexOf(true)==-1){d3.selectAll(".circles").attr("class",function(d,i){return"circles "+ d.group;}).attr("fill",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).attr("stroke",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).style("opacity",1.00).style("fill-opacity",0.50);}
else{d3.selectAll('.circles').attr("class",function(d,i){return"circles disabled "+ d.group;}).style("stroke","solid").style("stroke","#666").style("fill","#666").style("opacity",0.5).style("pointer-events","none");var index=dvc.config.vars.groups.indexOf(dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]);var color=dvc.config.vars.grpColorArray[index];d3.selectAll('.circles'+'.'+ dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]).attr("class","circles "+ dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]).style("stroke","solid").style("stroke",color).style("fill",color).style("opacity",1.00).style("fill-opacity",0.50).style("pointer-events","auto");}
removeTooltip();});}
return;}
function getSelectedReferenceInfo(fid){dvc.selectedCircleID='';dvc.circleClass='';dvc.circleClass=($('#'+ fid).attr('class')).replace("voronoiTEMP ",'').replace("voronoi ",'').replace("disabled ",'');dvc.selectedCircleID=fid.replace("voronoi",'circle');dvc.selectedCircleID=dvc.selectedCircleID.replace("TEMP",'');dvc.index=dvc.config.vars.groups.indexOf(dvc.circleClass);dvc.color=dvc.config.vars.grpColorArray[dvc.index];return;}
function transitionData()
{$(".tick").remove();d3.select("#voronoiGridFull").remove();d3.select("#voronoiGridTemp").remove();d3.select("#xAxisLabel").text("$ Health Spending Per Capita");d3.select("#yAxisLabel").text("Life Expectancy at Birth");dvc.LeastSquareArray_XY=[];dvc.LeastSquareArray_XX=[];dvc.LeastSquareArray_X=[];dvc.LeastSquareArray_Y=[];dvc.filteredLeastSquareArray_XY=[];dvc.filteredLeastSquareArray_XX=[];dvc.filteredLeastSquareArray_X=[];dvc.filteredLeastSquareArray_Y=[];dvc.regressionSlopeGradient=0;dvc.sigmaXY=0;dvc.sigmaXX=0;dvc.sigmaX=0;dvc.sigmaY=0;dvc.minX=0;dvc.maxX=0;dvc.xData=[];dvc.yData=[];dots.forEach(function(d,i){var x=+d[dvc.selectedXVariableIndex];var y=+d[dvc.selectedYVariableIndex];dvc.xData.push(+d[dvc.selectedXVariableIndex]);dvc.yData.push(+d[dvc.selectedYVariableIndex]);});if(dvc.config.essential.AxisScale=="auto_zero_max"){dvc.xDomain=[0,Math.ceil(d3.max(dvc.xData)/dvc.config.essential.xAxisScaleDivisor)*dvc.config.essential.xAxisScaleDivisor ];dvc.yDomain=[0,Math.ceil(d3.max(dvc.yData)/dvc.config.essential.yAxisScaleDivisor)*dvc.config.essential.yAxisScaleDivisor ];}
else if(dvc.config.essential.AxisScale=="auto_min_max"){dvc.xMin=Math.floor(d3.min(dvc.xData)/dvc.config.essential.xAxisScaleDivisor)*dvc.config.essential.xAxisScaleDivisor -1;dvc.xMax=Math.ceil(d3.max(dvc.xData)/dvc.config.essential.xAxisScaleDivisor)*dvc.config.essential.xAxisScaleDivisor;dvc.yMin=Math.floor(d3.min(dvc.yData)/dvc.config.essential.yAxisScaleDivisor)*dvc.config.essential.yAxisScaleDivisor;dvc.yMax=Math.ceil(d3.max(dvc.yData)/dvc.config.essential.yAxisScaleDivisor)*dvc.config.essential.yAxisScaleDivisor;dvc.xDomain=[dvc.xMin,dvc.xMax];dvc.yDomain=[dvc.yMin,dvc.yMax];}
else{dvc.xDomain=dvc.config.essential.AxisScale;dvc.yDomain=dvc.config.essential.AxisScale;}
if(dvc.selectedAxisLimitVariable=="Fixed"){dvc.xDomain=[dvc.xMin,dvc.xMax];dvc.yDomain=[dvc.yMin,dvc.yMax];}
else if(dvc.selectedAxisLimitVariable=="Data"){dvc.xDomain=[(Math.floor(d3.min(dvc.xData)/1)*1 )-1, Math.ceil(d3.max(dvc.xData)/1)*1 ];dvc.yDomain=[Math.floor(d3.min(dvc.yData)/1)*1 , Math.ceil(d3.max(dvc.yData)/1)*1 ];}
x.domain(dvc.xDomain);y.domain(dvc.yDomain);dvc.xAxis=d3.svg.axis().scale(x).orient("bottom").ticks(num_ticksx).tickFormat(d3.format(",."+ dvc.config.essential.xaxislabelPrecison+"f"));dvc.yAxis=d3.svg.axis().scale(y).orient("left").ticks(num_ticksy).tickFormat(d3.format(",."+ dvc.config.essential.yaxislabelPrecison+"f"));calculateYValues();d3.select("#focusXAxis").transition().duration(1000).call(dvc.xAxis);d3.select("#focusYAxis").transition().duration(1000).call(dvc.yAxis);svg.select("#horiReferenceLine").transition().duration(1000).attr("x1",x(dvc.xDomain[0])).attr("x2",x(dvc.xDomain[1])).attr("y1",margin.top+ y(dvc.config.optional.yline[dvc.selectedXVariableIndex/2])).attr("y2",margin.top+ y(dvc.config.optional.yline[dvc.selectedXVariableIndex/2]));svg.select("#vertReferenceLine").transition().duration(1000).attr("x1",x(dvc.config.optional.xline[dvc.selectedXVariableIndex/2])).attr("x2",x(dvc.config.optional.xline[dvc.selectedXVariableIndex/2])).attr("y1",margin.top+ y(dvc.yDomain[0])).attr("y2",margin.top+ y(dvc.yDomain[1]));svg.select("#horizlabel").transition().duration(1000).attr("y",margin.top+ y(dvc.config.optional.yline[dvc.selectedXVariableIndex/2])-5).attr("x",x(dvc.xDomain[1]));svg.select("#vertlabel").transition().duration(1000).attr("x",x(dvc.config.optional.xline[dvc.selectedXVariableIndex/2])-5).attr("y",y(dvc.yDomain[1])+margin.top+15);svg.selectAll(".annotext").transition().duration(1000).attr("y",function(d,i){return y(dvc.config.essential.annotationXY[i][dvc.selectedYVariableIndex])+ margin.top}).attr("x",function(d,i){return x(dvc.config.essential.annotationXY[i][dvc.selectedXVariableIndex])})
var dataToUse;if(dvc.booleanButtons.indexOf(true)==-1){dataToUse=dots;}
else{dataToUse=dvc.tempDotArray;}
var src;if(dvc.booleanButtons.indexOf(true)==-1){src="FULL";}
else{src="TEMP";}
svg.selectAll("circle").data(dots).transition().ease("linear").delay(function(d,i){return i*10;}).duration(500).attr("cx",function(d,i){return x(d[dvc.selectedXVariableIndex]);}).attr("cy",function(d,i){return y(d[dvc.selectedYVariableIndex])+dvc.Padding_top;}).attr("r",function(d,i){return 5}).attr("fill",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).attr("stroke",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}});if(typeof dvc.tempDotArray!=='undefined'){svg.selectAll(".TEMPcircles").data(dvc.tempDotArray).transition().ease("linear").delay(function(d,i){return i*10;}).duration(500).attr("cx",function(d,i){return x(d[dvc.selectedXVariableIndex]);}).attr("cy",function(d,i){return y(d[dvc.selectedYVariableIndex])+dvc.Padding_top;}).attr("r",function(d,i){return 5}).style("fill",function(d,i){return"none";}).style("stroke",function(d,i){return"none";}).style("opacity",0.0).style("fill-opacity",0.0);}
var layerToSelect='';var voronoi=d3.geom.voronoi().x(function(d,i){return x(d[dvc.selectedXVariableIndex]);}).y(function(d,i){return y(d[dvc.selectedYVariableIndex])+dvc.Padding_top;}).clipExtent([[margin.left-5,margin.top-5],[chart_width-margin.left+ 15,height+ margin.top+ 5]]);if(dvc.selectedXVariable!=dvc.selectedYVariable){svg.append("g").attr("id",function(){if(dvc.booleanButtons.indexOf(true)==-1){layerToSelect="voronoiGridFull";return"voronoiGridFull";}
else{layerToSelect="voronoiGridTemp";return"voronoiGridTemp";}});d3.select("#"+ layerToSelect).selectAll("path").data(voronoi(dataToUse)).enter().append("path").attr("d",function(d,i){if(typeof d!=='undefined'){return"M"+ d.join("L")+"Z";}
else{}}).datum(function(d,i){if(typeof d!=='undefined'){return d.point;}
else{}}).attr("class",function(d,i){if(typeof d!=='undefined'){if(dvc.booleanButtons.indexOf(true)==-1){return"voronoi "+ d.group;}
else{return"voronoiTEMP "+ d.group;}}
else{}}).attr("id",function(d,i){if(dvc.booleanButtons.indexOf(true)==-1){return"voronoi"+ i;}
else{return"voronoiTEMP"+ i;}}).style("stroke",function(d,i){return"none";}).style("fill","none").style("pointer-events","all").on("mouseover",function(d,i){d3.select("#SelectedyAxisValueLabel").remove();d3.select("#SelectedxAxisValueLabel").remove();getSelectedReferenceInfo(this.id);if(($('#'+ dvc.selectedCircleID).attr("class").indexOf("disabled")==-1&&src=="FULL")||(src=="TEMP")&&(graphic.width()>dvc.config.optional.mobileBreakpoint)){if(src=="FULL"){d3.selectAll('.circles').style("opacity",0.5).style("fill-opacity",0.125);d3.select('#'+ dvc.selectedCircleID).style("opacity",1.0).style("fill-opacity",1.0);}
var xValue=d[dvc.selectedXVariableIndex];var yValue=d[dvc.selectedYVariableIndex];showTooltip(d,this.id,xValue,yValue,src);}}).on("mouseout",function(d,i){if(dvc.booleanButtons.indexOf(true)==-1){d3.selectAll(".circles").attr("class",function(d,i){return"circles "+ d.group;}).style("fill",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).style("stroke",function(d,i){if(i==32){return"#F85F73"}else{return"#2b8cbe"}}).style("opacity",1.00).style("fill-opacity",0.50);}
else{d3.selectAll('.circles').attr("class",function(d,i){return"circles disabled "+ d.group;}).style("stroke","solid").style("stroke","#666").style("fill","#666").style("opacity",0.5).style("pointer-events","none");var index=dvc.config.vars.groups.indexOf(dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]);var color=dvc.config.vars.grpColorArray[index];d3.selectAll('.circles'+'.'+ dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]).attr("class","circles "+ dvc.config.vars.groups[dvc.booleanButtons.indexOf(true)]).style("stroke","solid").style("stroke",color).style("fill",color).style("opacity",1.00).style("fill-opacity",0.50).style("pointer-events","auto");}
removeTooltip();});}
dvc.xticks=svg.selectAll('#focusXAxis').selectAll('.tick');dvc.xticks.append('svg:line').attr('id',"xAxisTicks").attr('y0',0).attr('y1',-height).attr('x1',0).attr('x2',0).style("opacity",0.33);dvc.yticks=svg.selectAll('#focusYAxis').selectAll('.tick');dvc.yticks.append('svg:line').attr('id',"yAxisTicks").attr('y0',0).attr('y1',0).attr('x1',0).attr('x2',chart_width- margin.left).style("opacity",0.33);setTimeout(function(){d3.selectAll(".TEMPcircles").style("display","inline");},1500);return;}
$(document).ready(function(){$("#nationUK").hover(function(){$('#voronoi32').triggerSVGEvent('mouseover');},function(){$('#voronoi32').triggerSVGEvent('mouseout');});});function showTooltip(d,fid,xVal,yVal,src){var element;if(src=="FULL"){element=d3.select("#"+ dvc.selectedCircleID);}
else if(src=="TEMP"){element=d3.select("#"+ dvc.selectedCircleID.replace("circle","TEMPcircle"));}
else{}
if(graphic.width()>dvc.config.optional.mobileBreakpoint){function numberWithCommas(x){return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g,",");}
$(element).popover({placement:'auto top',container:'#graphic',id:"toolTip",trigger:'manual',html:true,content:function(){return"<span style='font-size: 14px; text-align: center;'><b>"+ d.name+"</b></span><br><span style='font-size: 14px; text-align: center;'><b>Import: £"+ numberWithCommas(d[dvc.selectedXVariableIndex])+"m</b></span><br><span style='font-size: 14px; text-align: center;'><b>Export: £"+ numberWithCommas(d[dvc.selectedYVariableIndex])+"m</b></span>";}});$(element).popover('show');}
else{}
return;}
function showCoords(){}
function removeTooltip(){$('.popover').each(function(){$(this).remove();});return;}
function getState(fid){if(fid=="equality"){if(dvc.boolEqualityLine==false){d3.select("#equalityLine").style("display","inline");dvc.boolEqualityLine=true;}
else{dvc.boolEqualityLine=false;}}
else if(fid=="regression"){if(dvc.boolRegressionLine==false){d3.select("#regressionLine").style("display","inline");dvc.boolRegressionLine=true;}
else{dvc.boolRegressionLine=false;}}
else{}
return;}
if(Modernizr.inlinesvg)
{d3.json("data/config.json",function(error,json)
{dvc.config=json;buildUI();dvc.selectedXVariable="Healthy Life Expectancy";dvc.selectedXVariableIndex=dvc.config.vars.variables.indexOf(dvc.selectedXVariable);dvc.selectedXUnits="years";dvc.selectedYVariable="Inequality within local authority";dvc.selectedYVariableIndex=dvc.config.vars.variables.indexOf(dvc.selectedYVariable);dvc.selectedYUnits="Years";dvc.selectedAxisLimitVariable="Data";dvc.limitTypeIndex=dvc.config.vars.axisLimits.indexOf(dvc.selectedAxisLimitVariable);dvc.selectedGroup="Show all";dvc.selectedGroupIndex=dvc.config.vars.groups.indexOf(dvc.selectedGroup);dvc.booleanButtons=[];dvc.config.vars.groups.forEach(function(d,i){dvc.booleanButtons[i]=false;})
dvc.boolEqualityLine=false;dvc.boolRegressionLine=false;d3.csv(dvc.config.essential.graphic_data_url,function(error,data){graphic_data=data;pymChild=new pym.Child({renderCallback:drawGraphic});})})}
else{pymChild=new pym.Child();d3.select("#graphic").empty();d3.select("#graphic").append("img").attr("src","fallback1.png");if(pymChild){pymChild.sendHeight();}}